### ISSUE TITLE
关于训练过程中Loss突然变大的问题

### ISSUE THREAD

**Issue by ShaochengShen** [bubbliiiing/ddpm-pytorch#17]
想请问一下博主，我使用LSUN的数据集，初始学习率2e-04，使用adam优化器，为什么会有训练到一半突然loss增大的问题。
期待您的回复。

**Comment by ShaochengShen** [comment]
![image](https://github.com/bubbliiiing/ddpm-pytorch/assets/94623045/a5248088-0307-4d3f-8d68-d595b90e95c8)

**Comment by bubbliiiing** [comment]
可能是……学习率太大了？

**Comment by ShaochengShen** [comment]
感谢回复 调整了学习率之后训练好多了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月28日(周五) 凌晨0:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bubbliiiing/ddpm-pytorch] 关于训练过程中Loss突然变大的问题 (Issue #17)




 
可能是……学习率太大了？
