### ISSUE TITLE
灰度图能不能训练呀

### ISSUE THREAD

**Issue by zhoujiayi1017** [bubbliiiing/ddpm-pytorch#8]
虽然在utils.py里看到了def cvtColor(image)，但是这个函数好像预测时才用到了，所以好奇训练的话能不能用灰度数据集呢…如果可以的话需要改哪些地方呀（如果能大概回复一下就很感谢了）

**Comment by zhoujiayi1017** [comment]
自问自答。。。似乎直接把灰度图当成RGB就可以了呢

**Comment by kikucxj** [comment]
> 

什么都不用改吗，直接就可以了嘛，我也想生成灰度图

**Comment by bubbliiiing** [comment]
额，会生成rgb图，但是可以再转成灰度图

**Comment by zhoujiayi1017** [comment]
> > 
> 
> 
> 
> 什么都不用改吗，直接就可以了嘛，我也想生成灰度图

我也就改了一点点训练的参数...epoch200多以后生成的图片里基本上没彩色了

**Comment by bubbliiiing** [comment]
0 0额
